ALTER TABLE queue_entries
  ADD COLUMN IF NOT EXISTS avoid_player_id UUID REFERENCES players (id) ON DELETE SET NULL;

ALTER TABLE matches
  ADD COLUMN IF NOT EXISTS is_repeat_pairing BOOLEAN NOT NULL DEFAULT FALSE;
