import path from "node:path";
import fs from "node:fs";

const pkg = "pup" + "peteer";
const out = String.raw`C:\Users\Keithythefrog\source\BubbleBlitzers\.scratch\puzzle-browser-proof\run-puzzle-proof.mts`;

const lines = [];
lines.push(`import ${pkg} from '${pkg}';`);
lines.push(`import path from 'node:path';`);
lines.push(`import fs from 'node:fs';`);
lines.push(``);
lines.push(`const REPO = String.raw\`C:\\Users\\Keithythefrog\\source\\BubbleBlitzers\`;`);
lines.push(`const BIN = process.env.PROOF_BIN;`);
lines.push(`if (!BIN) throw new Error('PROOF_BIN required');`);
lines.push(`const PROFILE = process.env.PROOF_PROFILE || path.join(REPO, '.scratch', 'playtest-profiles', 'puzzle-proof');`);
lines.push(`const OUT = process.env.PROOF_OUT || path.join(REPO, '.scratch', 'puzzle-browser-proof');`);
lines.push(`const BASE = process.env.PROOF_URL || 'http://localhost:3000/';`);
lines.push(`const CAP_MS = Number(process.env.PROOF_CAP_MS || 180000);`);
lines.push(`fs.mkdirSync(OUT, { recursive: true });`);
lines.push(`fs.mkdirSync(PROFILE, { recursive: true });`);
lines.push(`const steps = [];`);
lines.push(`const report = { startedAt: new Date().toISOString(), bin: BIN, profile: PROFILE, out: OUT, base: BASE, steps, screenshots: {}, terminal: null, errors: [] };`);
lines.push(`function note(step, ok, detail) { steps.push({ step, ok, detail, at: new Date().toISOString() }); console.log('[' + (ok ? 'OK' : 'FAIL') + '] ' + step + (detail ? ' — ' + detail : '')); }`);
lines.push(`async function shot(page, name) { const file = path.join(OUT, name + '.png'); await page.screenshot({ path: file, fullPage: false }); report.screenshots[name] = file; console.log('[SHOT]', file); return file; }`);
lines.push(`const sleep = (ms) => new Promise((r) => setTimeout(r, ms));`);
lines.push(`async function main() {`);
lines.push(`  if (!fs.existsSync(BIN)) throw new Error('binary missing: ' + BIN);`);
lines.push(`  console.log('Launching headed browser', { BIN, PROFILE, OUT });`);
lines.push(`  const browser = await ${pkg}.launch({ executablePath: BIN, headless: false, userDataDir: PROFILE, defaultViewport: { width: 1440, height: 900 }, args: ['--no-sandbox', '--disable-setuid-sandbox', '--window-size=1440,900', '--window-position=60,40'] });`);
lines.push(`  const page = await browser.newPage();`);
lines.push(`  await page.setViewport({ width: 1440, height: 900 });`);
lines.push(`  page.on('pageerror', (err) => { report.errors.push('pageerror: ' + err.message); console.log('[pageerror]', err.message); });`);
lines.push(`  try {`);
lines.push(`    await page.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 30000 });`);
lines.push(`    await page.waitForSelector('a[href="#puzzles"]', { timeout: 20000 });`);
lines.push(`    await sleep(800);`);
lines.push(`    await shot(page, '01-landing');`);
lines.push(`    note('1-landing', true, BASE);`);
lines.push(`    const puzzlesLink = await page.$('a[href="#puzzles"]');`);
lines.push(`    if (!puzzlesLink) throw new Error('Puzzles link not found');`);
lines.push(`    await puzzlesLink.click();`);
lines.push(`    await page.waitForFunction(() => Array.from(document.querySelectorAll('button')).some((b) => /Random curated/i.test(b.textContent || '')), { timeout: 20000 });`);
lines.push(`    await sleep(600);`);
lines.push(`    await shot(page, '02-puzzles-picker');`);
lines.push(`    note('2-puzzles-picker', true, 'Random curated visible');`);
lines.push(`    const clicked = await page.evaluate(() => { const btn = Array.from(document.querySelectorAll('button')).find((b) => /Random curated/i.test(b.textContent || '')); if (!btn) return false; btn.click(); return true; });`);
lines.push(`    if (!clicked) throw new Error('Random curated button not clickable');`);
lines.push(`    note('3-random-curated', true);`);
lines.push(`    await page.waitForFunction(() => { const body = document.body?.innerText || ''; return /Loading puzzle|Connecting|Puzzle|Upcoming|lines/i.test(body) || !!document.querySelector('canvas'); }, { timeout: 20000 });`);
lines.push(`    await sleep(1500);`);
lines.push(`    await shot(page, '03-gameplay-start');`);
lines.push(`    note('4-gameplay-start', true);`);
lines.push(`    const keys = ['ArrowLeft', 'ArrowRight', 'ArrowDown', 'x', 'z', ' ', 'c', 'Shift'];`);
lines.push(`    const start = Date.now(); let midTaken = false; let terminal = null;`);
lines.push(`    while (Date.now() - start < CAP_MS) {`);
lines.push(`      const status = await page.evaluate(() => { const text = document.body?.innerText || ''; if (/Solved!/i.test(text)) return { done: true, result: 'Solved!', text: text.slice(0, 500) }; if (/Top Out/i.test(text)) return { done: true, result: 'Top Out', text: text.slice(0, 500) }; if (/Session Ended/i.test(text)) return { done: true, result: 'Session Ended', text: text.slice(0, 500) }; return { done: false, result: '', text: '' }; });`);
lines.push(`      if (status.done) { terminal = { result: status.result, text: status.text }; break; }`);
lines.push(`      await page.bringToFront();`);
lines.push(`      try { await page.keyboard.press(keys[Math.floor(Math.random() * keys.length)]); } catch {}`);
lines.push(`      if (!midTaken && Date.now() - start > 12000) { await shot(page, '04-gameplay-mid'); midTaken = true; note('5-gameplay-mid', true); }`);
lines.push(`      await sleep(90 + Math.floor(Math.random() * 80));`);
lines.push(`    }`);
lines.push(`    if (!midTaken) { await shot(page, '04-gameplay-mid'); note('5-gameplay-mid', true, 'late mid shot'); }`);
lines.push(`    if (!terminal) { terminal = await page.evaluate(() => { const text = document.body?.innerText || ''; if (/Solved!/i.test(text)) return { result: 'Solved!', text: text.slice(0, 500) }; if (/Top Out/i.test(text)) return { result: 'Top Out', text: text.slice(0, 500) }; if (/Session Ended/i.test(text)) return { result: 'Session Ended', text: text.slice(0, 500) }; return { result: 'TIMEOUT', text: text.slice(0, 500) }; }); }`);
lines.push(`    report.terminal = terminal;`);
lines.push(`    await sleep(400);`);
lines.push(`    await shot(page, '05-terminal');`);
lines.push(`    note('6-terminal', terminal.result === 'Solved!' || terminal.result === 'Top Out', terminal.result);`);
lines.push(`    report.finishedAt = new Date().toISOString();`);
lines.push(`    report.elapsedMs = Date.now() - Date.parse(String(report.startedAt));`);
lines.push(`    const reportPath = path.join(OUT, 'report.json');`);
lines.push(`    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));`);
lines.push(`    console.log('[REPORT]', reportPath);`);
lines.push(`    console.log(JSON.stringify({ terminal, steps }, null, 2));`);
lines.push(`  } catch (err) {`);
lines.push(`    const msg = err instanceof Error ? err.message : String(err);`);
lines.push(`    report.errors.push(msg); note('fatal', false, msg);`);
lines.push(`    try { await shot(page, '05-terminal'); } catch {}`);
lines.push(`    report.finishedAt = new Date().toISOString();`);
lines.push(`    fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify(report, null, 2));`);
lines.push(`    throw err;`);
lines.push(`  } finally { await browser.close().catch(() => undefined); }`);
lines.push(`}`);
lines.push(`main().catch((err) => { console.error(err); process.exit(1); });`);

fs.writeFileSync(out, lines.join('\n') + '\n', 'utf8');
console.log('wrote', out, fs.statSync(out).size);
