import { buildAuthoredLevels } from '../server/puzzle/catalog/authoredLevels.js';
import { runPuzzleBaselineBatch } from '../server/puzzle/puzzleBaselineBatch.js';
import { DEFAULT_PUZZLE_VALIDATION_CANDIDATES } from '../server/puzzle/puzzleValidationArtifact.js';

export const DOUBLED_TIMELINES: Record<string, any[]> = {
  'authored-cheese-keyhole': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 4, kind: 'magnet' },
    { afterPieces: 5, kind: 'snag' },
    { afterPieces: 6, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 7, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
  ],
  'authored-well-freeze': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 3, kind: 'curtain' },
    { afterPieces: 4, kind: 'magnet' },
    { afterPieces: 5, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 6, kind: 'snag' },
  ],
  'authored-skew-stairs': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 3, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'magnet' },
    { afterPieces: 6, kind: 'sticky' },
    { afterPieces: 8, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 9, kind: 'snag' },
  ],
  'authored-pulse-garbage': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'magnet' },
    { afterPieces: 9, kind: 'sticky' },
    { afterPieces: 11, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 14, kind: 'curtain' },
    { afterPieces: 16, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 19, kind: 'snag' },
  ],
  'authored-cheese-ladder': [
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 6, kind: 'snag' },
    { afterPieces: 8, kind: 'magnet' },
    { afterPieces: 10, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 12, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
  ],
  'authored-dig-shaft': [
    { afterPieces: 3, kind: 'retrim' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 18 } },
    { afterPieces: 10, kind: 'curtain' },
    { afterPieces: 14, kind: 'magnet' },
    { afterPieces: 18, kind: 'garbage', params: { lines: 1, delayTicks: 18 } },
    { afterPieces: 22, kind: 'sticky' },
    { afterPieces: 26, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 30, kind: 'snag' },
    { afterPieces: 34, kind: 'magnet' },
    { afterPieces: 38, kind: 'garbage', params: { lines: 1, delayTicks: 18 } },
  ],
  'authored-tslot-setup': [
    { afterPieces: 3, kind: 'sticky' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 9, kind: 'snag' },
    { afterPieces: 12, kind: 'retrim' },
    { afterPieces: 15, kind: 'magnet' },
    { afterPieces: 18, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 20, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 22, kind: 'curtain' },
  ],
  'authored-four-wide': [
    { afterPieces: 3, kind: 'magnet' },
    { afterPieces: 6, kind: 'sticky' },
    { afterPieces: 10, kind: 'snag' },
    { afterPieces: 13, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 16, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 20, kind: 'magnet' },
  ],
  'authored-hold-discipline': [
    { afterPieces: 3, kind: 'retrim' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 8, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 11, kind: 'magnet' },
    { afterPieces: 14, kind: 'snag' },
    { afterPieces: 17, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 20, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 24, kind: 'curtain' },
  ],
  'authored-poison-beat': [
    { tick: 90, kind: 'poison', params: { variant: 2 } },
    { tick: 170, kind: 'wildcard', params: { variant: 2 } },
    { afterPieces: 6, kind: 'sticky' },
    { afterPieces: 10, kind: 'snag' },
    { afterPieces: 15, kind: 'poison', params: { variant: 2 } },
    { afterPieces: 18, kind: 'sticky' },
    { afterPieces: 22, kind: 'purge', params: { variant: 2 } },
    { afterPieces: 25, kind: 'snag' },
    { afterPieces: 28, kind: 'magnet' },
    { afterPieces: 32, kind: 'curtain' },
  ],
  'authored-curtain-drop': [
    { tick: 60, kind: 'retrim' },
    { tick: 480, kind: 'curtain' },
    { tick: 1200, kind: 'curtain' },
    { tick: 1800, kind: 'magnet' },
    { afterPieces: 10, kind: 'garbage', params: { lines: 1, delayTicks: 18 } },
    { afterPieces: 25, kind: 'sticky' },
    { afterPieces: 45, kind: 'garbage', params: { lines: 1, delayTicks: 18 } },
    { afterPieces: 70, kind: 'snag' },
  ],
  'authored-late-i-well': [
    { afterPieces: 4, kind: 'retrim' },
    { afterPieces: 8, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 11, kind: 'magnet' },
    { afterPieces: 14, kind: 'sticky' },
    { afterPieces: 17, kind: 'snag' },
    { afterPieces: 20, kind: 'curtain' },
    { afterPieces: 23, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 26, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
  ],
  'import-jstris-checkboard': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 3, kind: 'sticky' },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'snag' },
    { afterPieces: 9, kind: 'magnet' },
    { afterPieces: 11, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-ultimate-29-combo': [
    { tick: 120, kind: 'retrim' },
    { tick: 240, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { tick: 360, kind: 'sticky' },
    { tick: 480, kind: 'magnet' },
    { tick: 600, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { tick: 750, kind: 'magnet' },
    { tick: 900, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 5, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 12, kind: 'curtain' },
    { afterPieces: 20, kind: 'snag' },
  ],
  'import-fumen-c4w-3res': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'snag' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'sticky' },
    { afterPieces: 6, kind: 'magnet' },
    { afterPieces: 7, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-perfect-clear-how': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 3, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'magnet' },
    { afterPieces: 6, kind: 'sticky' },
    { afterPieces: 8, kind: 'snag' },
    { afterPieces: 9, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-clear-the-rainbow': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 3, kind: 'magnet' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'snag' },
  ],
  'import-jstris-lspins-easy': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 3, kind: 'sticky' },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 6, kind: 'snag' },
    { afterPieces: 8, kind: 'magnet' },
    { afterPieces: 9, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-cheese-10': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'poison', params: { variant: 2 } },
    { afterPieces: 3, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 4, kind: 'purge', params: { variant: 2 } },
    { afterPieces: 5, kind: 'sticky' },
    { afterPieces: 6, kind: 'magnet' },
    { afterPieces: 7, kind: 'snag' },
    { afterPieces: 8, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
  ],
  'import-jstris-clog': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'curtain' },
    { afterPieces: 10, kind: 'sticky' },
    { afterPieces: 12, kind: 'snag' },
    { afterPieces: 14, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 17, kind: 'magnet' },
    { afterPieces: 19, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-s-spin-triple': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'snag' },
    { afterPieces: 6, kind: 'curtain' },
    { afterPieces: 7, kind: 'magnet' },
  ],
  'import-jstris-drilltris-1': [
    { afterPieces: 1, kind: 'garbage', params: { lines: 1, delayTicks: 6 } },
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 2, kind: 'snag' },
  ],
  'import-jstris-drilltris-2': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 1, kind: 'garbage', params: { lines: 1, delayTicks: 6 } },
    { afterPieces: 2, kind: 'snag' },
    { afterPieces: 2, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-srs-tower': [
    { afterPieces: 2, kind: 'poison', params: { variant: 2 } },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'wildcard', params: { variant: 2 } },
    { afterPieces: 7, kind: 'sticky' },
    { afterPieces: 9, kind: 'snag' },
    { afterPieces: 12, kind: 'magnet' },
  ],
  'import-jstris-mash-space': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 2, kind: 'snag' },
    { afterPieces: 3, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 4, kind: 'sticky' },
    { afterPieces: 5, kind: 'magnet' },
    { afterPieces: 6, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-srs-training': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 6, kind: 'curtain' },
    { afterPieces: 7, kind: 'sticky' },
    { afterPieces: 9, kind: 'magnet' },
    { afterPieces: 10, kind: 'snag' },
  ],
  'import-jstris-dt-cannon-practice': [
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 3, kind: 'retrim' },
    { afterPieces: 5, kind: 'snag' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 8, kind: 'magnet' },
    { afterPieces: 9, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-godspin': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 3, kind: 'poison', params: { variant: 2 } },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'sticky' },
    { afterPieces: 10, kind: 'purge', params: { variant: 2 } },
    { afterPieces: 12, kind: 'magnet' },
    { afterPieces: 14, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 15, kind: 'snag' },
  ],
  'import-jstris-many-stsd': [
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 4, kind: 'magnet' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 8, kind: 'snag' },
    { afterPieces: 11, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 13, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 15, kind: 'magnet' },
    { afterPieces: 17, kind: 'retrim' },
    { afterPieces: 19, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 21, kind: 'curtain' },
  ],
  'import-jstris-tripz': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 4, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 6, kind: 'curtain' },
    { afterPieces: 8, kind: 'snag' },
    { afterPieces: 10, kind: 'sticky' },
    { afterPieces: 12, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 14, kind: 'magnet' },
    { afterPieces: 15, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-the-gutter': [
    { afterPieces: 1, kind: 'retrim' },
    { afterPieces: 3, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 5, kind: 'magnet' },
    { afterPieces: 6, kind: 'sticky' },
    { afterPieces: 7, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 8, kind: 'snag' },
  ],
  'import-jstris-1v1-downstack': [
    { afterPieces: 2, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 3, kind: 'sticky' },
    { afterPieces: 5, kind: 'magnet' },
    { afterPieces: 6, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'curtain' },
    { afterPieces: 8, kind: 'snag' },
  ],
  'import-jstris-aaron-s-t-spin-tower': [
    { afterPieces: 2, kind: 'retrim' },
    { afterPieces: 3, kind: 'sticky' },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'curtain' },
    { afterPieces: 9, kind: 'magnet' },
    { afterPieces: 12, kind: 'snag' },
    { afterPieces: 14, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 17, kind: 'retrim' },
    { afterPieces: 19, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 21, kind: 'magnet' },
  ],
  'import-jstris-dhd': [
    { tick: 90, kind: 'poison', params: { variant: 1 } },
    { tick: 210, kind: 'wildcard', params: { variant: 1 } },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 10, kind: 'snag' },
    { afterPieces: 15, kind: 'magnet' },
    { afterPieces: 18, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 22, kind: 'sticky' },
    { afterPieces: 25, kind: 'curtain' },
    { afterPieces: 28, kind: 'snag' },
    { afterPieces: 32, kind: 'freeze', params: { durationTicks: 360 } },
  ],
  'import-jstris-t-spin-triples': [
    { afterPieces: 2, kind: 'sticky' },
    { afterPieces: 3, kind: 'retrim' },
    { afterPieces: 5, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 7, kind: 'curtain' },
    { afterPieces: 9, kind: 'freeze', params: { durationTicks: 360 } },
    { afterPieces: 11, kind: 'snag' },
    { afterPieces: 13, kind: 'garbage', params: { lines: 1, delayTicks: 12 } },
    { afterPieces: 15, kind: 'magnet' },
  ],
};

const levels = buildAuthoredLevels();
let failures = 0;

for (let i = 0; i < levels.length; i++) {
  const level = levels[i];
  if (DOUBLED_TIMELINES[level.id]) {
    level.timeline = DOUBLED_TIMELINES[level.id];
  }

  const batch = runPuzzleBaselineBatch(level, [...DEFAULT_PUZZLE_VALIDATION_CANDIDATES]);
  const passed = batch.selected != null && batch.selected.report.solved;

  if (!passed) {
    failures++;
    console.error(`❌ FAILED: [#${i + 1}] ${level.id} ("${level.name}")`);
  } else {
    console.log(`✅ PASSED: [#${i + 1}] ${level.id} (profile=${batch.selected?.profile.id}, pieces=${batch.selected?.report.piecesUsed}, ticks=${batch.selected?.report.ticksUsed})`);
  }
}

console.log(`\nResult: ${levels.length - failures}/${levels.length} passed.`);
if (failures > 0) process.exit(1);
