name: Deploy BubbleBlitzers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RariAden-Hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Set game server URL
        run: echo '{"gameServerUrl":"${{ secrets.GAME_SERVER_URL }}"}' > public/game-config.json

      - name: Build client
        run: npm run build:client

      - name: Build replay viewer
        run: npm run build:replay

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "."
          target: "${{ secrets.SERVER_DEPLOY_PATH }}"
          rm: true
          exclude: "node_modules,.git"

      - name: Deploy server and client
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" > ${{ secrets.SERVER_DEPLOY_PATH }}/.env
            echo "REPLAYS_HOST_PATH=${{ secrets.REPLAYS_HOST_PATH }}" >> ${{ secrets.SERVER_DEPLOY_PATH }}/.env
            
            # Deploy Main Client
            mkdir -p ${{ secrets.CLIENT_DEPLOY_PATH }}
            rm -rf ${{ secrets.CLIENT_DEPLOY_PATH }}/*
            cp -r ${{ secrets.SERVER_DEPLOY_PATH }}/dist/client/. ${{ secrets.CLIENT_DEPLOY_PATH }}/
            
            # Deploy Replay Viewer
            mkdir -p ${{ secrets.REPLAY_DEPLOY_PATH }}
            rm -rf ${{ secrets.REPLAY_DEPLOY_PATH }}/*
            cp -r ${{ secrets.SERVER_DEPLOY_PATH }}/dist/replay-viewer/. ${{ secrets.REPLAY_DEPLOY_PATH }}/
            
            cd ${{ secrets.SERVER_DEPLOY_PATH }}
            docker compose up -d --build --force-recreate
